kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec: 
   replicas: 2
   selector: 
     matchLabels: 
       app: myspringboot
   template: 
      metadata:
        labels:
          app: myspringboot
      sepc:
        containers:
          - name: myspringboot
            image: vaibhavpatill/demoapplicattion:latest
            imagePullPolicy: always
            ports:
              - continerPort: 9099
           
          
            
                 
