kind: Service
apiVersion: v1
metadata: 
  name: myservice
  labels: 
     app: myspringboot
spec: 
  selector: 
    app: myspringboot
  type: LoadBalancer
  ports:
  - nodePort: 30036
    port: 80
    targetPort: 9099
